### ISSUE TITLE
Zoom-area crashes inside of a ion-slide

### ISSUE THREAD

**Issue by Ahmadre** [leonardosalles/ionic2-zoom-area#14]
I got my zoom-area inside of an ion-slide, but when i apply that on my image, the image is displayed on the bottom of the screen and isn't centered anymore. So my slide will break, when i apply an zoom-area :(

can you help me?

**Comment by leonardosalles** [comment]
@Ahmadre  thanks for this issue. It is planned to the next big release, will be released in the next few days, keep you eyes in this issue.

**Comment by Ahmadre** [comment]
@leonardosalles great thanks. now I wrapped the swiper-zoom-container outside my image, until you fix that, because i played around with the css, but it's a desaster, i just can't repair it ^^

**Comment by leonardosalles** [comment]
@Ahmadre no problems dude, it is already fixed now zoom area should work with all ionic elements, like card and others. I am finishing some new features to release it together.

**Comment by ahboyboy** [comment]
@leonardosalles any specific date for this new release? I am facing the ion-scroll issue too

**Comment by Ahmadre** [comment]
For your information:

![unbenannt](https://user-images.githubusercontent.com/18512224/40881758-caf6bfd6-66cf-11e8-8df1-d801c188c9a8.PNG)

This is how the images appear. My Code is:
```
<ion-slides #slides (ionSlideDidChange)="checkSlidePos()" pager>
  
        <ion-slide *ngFor="let image of images">
            <!-- <div class="swiper-zoom-container"> -->
              <zoom-area>
              <img id="galimg" src="{{imagePrefix}}{{image.filename}}" />
              </zoom-area>
            <!-- </div> -->
        </ion-slide>

    </ion-slides>
```

**Comment by jose-cabrera** [comment]
Hi! when will be the next big release? i'm having the exact same problem as @Ahmadre.

**Comment by leonardosalles** [comment]
It is planned to July. I am doing it from scratch to make better performance.

**Comment by pistou** [comment]
Any quick fix for it? I need it now, not in July tbh..

**Comment by leonardosalles** [comment]
It is not planned  to be inside an ion-slide, fixes will be not applied for that because it's a new feature that I am added to this new version. But feel free to submit a PR with this feature for actual version.

**Comment by Ahmadre** [comment]
@pistou He's doing this for FREE! So chill out

**Comment by pistou** [comment]
Here is my trick:

**home.html**
```html
<div #zoomWrapper class="zoom-wrapper">
    <zoom-area>
        <img [src]="path" [class]="asset.attributeClass" #zoomImg />
    </zoom-area>
</div>
```

**home.ts**
```typescript
@ViewChild('zoomWrapper') zoomWrapper: ElementRef;
@ViewChild('zoomImg') zoomImg: ElementRef;

ngOnInit() {
    if (this.zoomWrapper && this.zoomImg) {
        console.log("foo", this.zoomImg.nativeElement.clientHeight);
        this.zoomWrapper.nativeElement.style.height = this.zoomImg.nativeElement.clientHeight + 'px';
    }
}
```

**home.scss**
```scss
.zoom-wrapper {
    zoom-area {
        width: inherit !important;
        
        ion-content {
            width: inherit !important;
            background-color: transparent;
            
            .scroll-content {
                width: inherit !important;
                padding: 0 !important;
                
                .zoom {
                    width: inherit !important;
                    position: relative !important;
                }
            }
        }
    }
}
```
